In [47]:
import numpy as np
import pandas as pd

In [48]:
import requests

url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=ce66a9f468ee38efd796fdc9326e26f3&language=en-US&page=1"

response = requests.get(url)
data = response.json()

In [49]:
movies = data['results']

In [50]:
df = pd.DataFrame(movies)

In [51]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,49.7673,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.717,30002
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",37.4539,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.700,22666
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,25.9014,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.573,13726
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,23.7128,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,17249
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,20.1853,/2QXLVh32JKaWTjFJU3n8aIxRK9P.jpg,1957-04-10,12 Angry Men,False,8.556,9847
5,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",8.6017,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.546,305
6,False,/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",34.8421,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.533,18110
7,False,/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg,"[28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,52.0280,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.527,35396
8,False,/6N5d02quKqMKqvTpOdFmBDy9scY.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",12.4361,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.516,4567
9,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,30.4230,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.504,19003
10,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,37.4120,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.495,26243
11,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",34.3936,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.500,20330
12,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80, 35]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",29.4907,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,Pulp Fiction,False,8.486,29898
13,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,42.0294,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.477,12376
14,False,/2ssWTSVklAEc98frZUQhgtGHx7s.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,50.7880,/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg,2014-11-05,Interstellar,False,8.469,39226
15,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,23.8972,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-23,"The Good, the Bad and the Ugly",False,8.467,9512
16,False,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,30.5746,/saHP97rTPS5eLmrLQEcANmKrsFl.jpg,1994-06-23,Forrest Gump,False,8.463,29439
17,False,/gILte6Zd7m1YneIr6MVhh30S9pr.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",26.8501,/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg,1990-09-12,GoodFellas,False,8.452,14151
18,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,16.9791,/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg,1954-04-26,Seven Samurai,False,8.451,4153
19,False,/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0145,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.444,6427

In [52]:
df.head(2)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,49.7673,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.717,30002
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",37.4539,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.700,22666

In [53]:
df.shape

(20, 14)

In [54]:
df = df[['title', 'release_date', 'popularity', 'vote_average']]
df.head()

                      title release_date  popularity  vote_average
0  The Shawshank Redemption   1994-09-23     49.7673         8.717
1             The Godfather   1972-03-14     37.4539         8.700
2     The Godfather Part II   1974-12-20     25.9014         8.573
3          Schindler's List   1993-12-15     23.7128         8.567
4              12 Angry Men   1957-04-10     20.1853         8.556

In [55]:
df = pd.DataFrame()

In [56]:
df

Empty DataFrame
Columns: []
Index: []

In [57]:
for i in range(1,201):
    url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=ce66a9f468ee38efd796fdc9326e26f3&language=en-US&page={i}"
    response = requests.get(url)
    data = pd.DataFrame(response.json()['results'])
    df = pd.concat([df, data], ignore_index=True)

In [58]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,49.7673,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.717,30002
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",37.4539,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.700,22666
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,25.9014,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.573,13726
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,23.7128,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,17249
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,20.1853,/2QXLVh32JKaWTjFJU3n8aIxRK9P.jpg,1957-04-10,12 Angry Men,False,8.556,9847
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,False,/kz8uFk8AYDu4an8PhkdGLbVJXMi.jpg,"[53, 28, 35, 80, 18, 9648]",9812,en,Thursday,A former Los Angeles drug dealer moves far awa...,2.6244,/pbfBCMSzmKlAHZUDwsrtmG7GZP3.jpg,1998-09-25,Thursday,False,6.906,351
3996,False,/c31SAQjVMeVGv7mZsrw5BKGXj2P.jpg,"[16, 14, 878]",8953,ja,スチームボーイ,"In 1860s Britain, a boy inventor finds himself...",3.6157,/wszfXaMx74a91yRTBgO1fwSvMj3.jpg,2004-07-17,Steamboy,False,6.900,480
3997,False,/sAiTihJ8bjEqg8nYUIlTQUnVXuj.jpg,"[37, 12]",2023,en,Hidalgo,"Set in 1890, this is the story of a Pony Expre...",4.5559,/iGzENlBPYJEFWZnye4t3nqWSSp1.jpg,2004-02-04,Hidalgo,False,6.906,1318
3998,False,/hExTiLbfB93HwEwkeQxb3q4nHtQ.jpg,"[18, 10749]",1643,it,Ultimo tango a Parigi,A recently widowed American begins an anonymou...,3.9237,/dNgdUdNOWfHsZI3lDu6Epig7H2P.jpg,1972-12-15,Last Tango in Paris,False,6.906,1329
3999,False,/yXybBEC45p84D0Ky7GmQQYrclVr.jpg,"[28, 12, 14]",447404,en,Pokémon Detective Pikachu,In a world where people collect pocket-size mo...,7.4109,/uhWvnFgg3BNlcUz0Re1HfQqIcCD.jpg,2019-05-03,Pokémon Detective Pikachu,False,6.905,7281

In [59]:
df = df[['title','original_language','release_date', 'popularity', 'vote_average']]
df

,title,original_language,release_date,popularity,vote_average
0,The Shawshank Redemption,en,1994-09-23,49.7673,8.717
1,The Godfather,en,1972-03-14,37.4539,8.700
2,The Godfather Part II,en,1974-12-20,25.9014,8.573
3,Schindler's List,en,1993-12-15,23.7128,8.567
4,12 Angry Men,en,1957-04-10,20.1853,8.556
...,...,...,...,...,...
3995,Thursday,en,1998-09-25,2.6244,6.906
3996,Steamboy,ja,2004-07-17,3.6157,6.900
3997,Hidalgo,en,2004-02-04,4.5559,6.906
3998,Last Tango in Paris,it,1972-12-15,3.9237,6.906
3999,Pokémon Detective Pikachu,en,2019-05-03,7.4109,6.905

In [60]:
df.to_csv("top_rated_movies.csv", index=False)